-- Postgres baseline script (idempotent)
-- Applies the current schema for PostgreSQL and marks existing EF migrations as applied
-- Usage: psql "host=... user=... dbname=..." -f postgres_baseline.sql

BEGIN;

-- __EFMigrationsHistory
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" varchar(150) NOT NULL,
    "ProductVersion" varchar(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Applicants
CREATE TABLE IF NOT EXISTS "Applicants" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstName" text NOT NULL,
    "lastName" text NOT NULL,
    "email" text NOT NULL,
    "password" text NOT NULL,
    "phone" text NOT NULL,
    "streetAddress" text NOT NULL,
    "city" text NOT NULL,
    "state" text NOT NULL,
    "country" text NOT NULL,
    "zipCode" varchar(10) NOT NULL,
    "AppliedAt" timestamptz NOT NULL DEFAULT now(),
    "JobId" integer NOT NULL DEFAULT 0,
    "ResumeText" text NOT NULL DEFAULT '',
    "ResumeUrl" text NOT NULL DEFAULT '',
    "CoverLetter" text NOT NULL DEFAULT '',
    "LinkedInProfile" text NOT NULL DEFAULT '',
    "PortfolioUrl" text NOT NULL DEFAULT '',
    "Message" text NOT NULL DEFAULT ''
);

-- Jobs
CREATE TABLE IF NOT EXISTS "Jobs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "PostedAt" timestamptz NOT NULL DEFAULT now(),
    "Benefits" text,
    "EmploymentType" text NOT NULL DEFAULT '',
    "Location" text NOT NULL DEFAULT '',
    "Requirements" text NOT NULL DEFAULT '',
    "Responsibilities" text NOT NULL DEFAULT '',
    "SalaryRangeMin" integer NOT NULL DEFAULT 0,
    "SalaryRangeMax" integer NOT NULL DEFAULT 0,
    "VendorName" text NOT NULL DEFAULT '',
    "Company" text NOT NULL DEFAULT '',
    "Url" text NOT NULL DEFAULT '',
    "SalaryRange" text NOT NULL DEFAULT '',
    "IsActive" boolean NOT NULL DEFAULT true,
    "ClosingDate" timestamptz NULL,
    "Views" integer NOT NULL DEFAULT 0,
    "ApplicantsCount" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NULL
);

-- Users
CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username" text NOT NULL,
    "PasswordHash" bytea NOT NULL,
    "PasswordSalt" bytea NOT NULL
);

-- Index and FK
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relname = 'IX_Applicants_JobId') THEN
        CREATE INDEX "IX_Applicants_JobId" ON "Applicants" ("JobId");
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Applicants_Jobs_JobId') THEN
        ALTER TABLE "Applicants"
            ADD CONSTRAINT "FK_Applicants_Jobs_JobId"
            FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE;
    END IF;
END $$;

-- Insert EF migration records (mark them as applied) ------------------------------------------------
-- Replace or extend this list if you have additional historical migrations

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT m.m, '7.0.11'
FROM (VALUES
    ('20250325160847_InitialCreate'),
    ('20250711194218_UpdateTables'),
    ('20250711203847_AddUsersTable'),
    ('20250716191907_Added Columns to Job Table'),
    ('20250717124709_Changed Salary to SalaryRangeMin and SalaryRangeMax'),
    ('20250911213524_update_new_db_and_added_Model.JobDescriptionRequest'),
    ('20250917224441_InitUsers'),
    ('20251230120000_MergeJobsApiModels')
) AS m(m)
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" h WHERE h."MigrationId" = m.m);

COMMIT;

-- End of script
