// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriPowersLLC.Models;

#nullable disable

namespace TriPowersLLC.Migrations
{
    [DbContext(typeof(JobDBContext))]
    partial class JobDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("TriPowersLLC.Models.Applicants", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AppliedAt");

                    b.Property<int>("JobId");

                    b.Property<string>("ResumeText")
                        .IsRequired();

                    b.Property<string>("city")
                        .IsRequired();

                    b.Property<string>("country")
                        .IsRequired();

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("firstName")
                        .IsRequired();

                    b.Property<string>("lastName")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<string>("phone")
                        .IsRequired();

                    b.Property<string>("state")
                        .IsRequired();

                    b.Property<string>("streetAddress")
                        .IsRequired();

                    b.Property<string>("zipCode")
                        .IsRequired();

                    // JobsApi application fields
                    b.Property<string>("ResumeUrl")
                        .IsRequired();

                    b.Property<string>("CoverLetter")
                        .IsRequired();

                    b.Property<string>("LinkedInProfile")
                        .IsRequired();

                    b.Property<string>("PortfolioUrl")
                        .IsRequired();

                    b.Property<string>("Message")
                        .IsRequired();

                    b.HasKey("id");

                    b.HasIndex("JobId");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("TriPowersLLC.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Benefits");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("EmploymentType")
                        .IsRequired();

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<DateTime>("PostedAt");

                    b.Property<string>("Requirements")
                        .IsRequired();

                    b.Property<string>("Responsibilities")
                        .IsRequired();

                    b.Property<int>("SalaryRangeMax");

                    b.Property<int>("SalaryRangeMin");

                    b.Property<string>("Title")
                        .IsRequired();

                    // JobsApi fields
                    b.Property<string>("Company")
                        .IsRequired();

                    b.Property<string>("Url")
                        .IsRequired();

                    b.Property<string>("SalaryRange")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("ClosingDate");

                    b.Property<int>("Views");

                    b.Property<int>("ApplicantsCount");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("VendorName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("TriPowersLLC.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired();

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TriPowersLLC.Models.Applicants", b =>
                {
                    b.HasOne("TriPowersLLC.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });
#pragma warning restore 612, 618
        }
    }
}
